server:
  port: ${PORT:8889}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/grapematstar/sample-spring-cloud-config-repo.git
          username: ${github.username}
          password: ${github.password}
          clone-on-start: true
