spring:
  application:
    name: gateway-service
---
spring:
  profiles: zone1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      registerWithEureka: false
      proferSameZoneEureka: true
  intstnace:
    metadataMap:
      zone: zone1

server:
  port: ${PORT:8765}

---
spring:
  profiles: zone2

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      registerWithEureka: false
      proferSameZoneEureka: true
  intstnace:
    metadataMap:
      zone: zone2

server:
  port: ${PORT:8766}

---
spring:
  profiles: zone3

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      registerWithEureka: false
      proferSameZoneEureka: true
  intstnace:
    metadataMap:
      zone: zone3

server:
  port: ${PORT:8767}
