spring:
  application:
    name: gateway-service

zuul:
  prefix: /api
  routes:
    client:
      path: /client/**
      serviceId: client-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
    registerWithEureka: false

server:
  port: ${PORT:8765}